apiVersion: v1
kind: Pod
metadata:
  name: kata-remote-example
  labels:
    app: nginx
  namespace: openshift-sandboxed-containers-operator
spec:
  runtimeClassName: kata-remote
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

